import type { Config } from 'tailwindcss'

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ContractLens Design System Colors (Nested)
        primary: {
          DEFAULT: '#041627',
          container: '#1A2B3C',
          fixed: '#D2E4FB',
        },
        secondary: {
          DEFAULT: '#505F76',
          container: '#D0E1FB',
        },
        surface: {
          DEFAULT: '#F7F9FB',
          container: '#ECEEF0',
          'container-low': '#F2F4F6',
          'container-high': '#E6E8EA',
          'container-highest': '#E0E3E5',
        },
        outline: {
          DEFAULT: '#74777D',
          variant: '#C4C6CD',
        },
        'on-surface': {
          DEFAULT: '#191C1E',
          variant: '#44474C',
        },
        error: {
          DEFAULT: '#BA1A1A',
          container: '#FFDAD6',
        },
        
        // Flat colors from Google Stitch designs (For direct matching)
        "primary-fixed": "#d2e4fb",
        "on-error-container": "#93000a",
        "tertiary": "#211200",
        "on-surface-flat": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "background": "#f7f9fb",
        "on-secondary-container": "#54647a",
        "outline-flat": "#74777d",
        "tertiary-fixed": "#feddb5",
        "inverse-on-surface": "#eff1f3",
        "on-primary": "#ffffff",
        "surface-dim": "#d8dadc",
        "surface-tint": "#4f6073",
        "on-secondary-fixed-variant": "#38485d",
        "inverse-primary": "#b7c8de",
        "on-surface-variant-flat": "#44474c",
        "primary-container-flat": "#1a2b3c",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#38485a",
        "surface-bright": "#f7f9fb",
        "on-tertiary-fixed": "#281802",
        "surface-container-high": "#e6e8ea",
        "secondary-container-flat": "#d0e1fb",
        "inverse-surface": "#2d3133",
        "on-primary-container": "#8192a7",
        "tertiary-container": "#38260b",
        "on-primary-fixed": "#0b1d2d",
        "secondary-fixed-dim": "#b7c8e1",
        "tertiary-fixed-dim": "#e1c29b",
        "on-tertiary-fixed-variant": "#584326",
        "on-tertiary-container": "#a88c69",
        "error-container-flat": "#ffdad6",
        "surface-variant": "#e0e3e5",
        "outline-variant-flat": "#c4c6cd",
        "on-background": "#191c1e",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#0b1c30",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#b7c8de",
        "surface-container-low": "#f2f4f6",
        "surface-container-flat": "#eceef0",
        "secondary-fixed": "#d3e4fe"
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        unit: 1,
        xl: 8,
        sm: 2,
        gutter: 3,
        lg: 6,
        md: 4,
        xs: 1,
      },
    },
  },
  plugins: [],
} satisfies Config
