import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useQuery, useMutation } from '@tanstack/react-query';
import api from '../services/api';

interface Contract {
  contract_id: string;
  filename: string;
  customer_name: string;
  contract_type: string;
  department: string;
  workflow_state: string;
  uploaded_at: string;
  approved_at?: string;
  published_at?: string;
}

export default function Repository() {
  const navigate = useNavigate();

  // Filters State
  const [selectedYear, setSelectedYear] = useState<string>('2024');
  const [selectedDepartments, setSelectedDepartments] = useState<string[]>(['Legal', 'Finance', 'Procurement']);
  const [contractType, setContractType] = useState<string>('All Types');
  const [minAccuracy, setMinAccuracy] = useState<number>(85);
  
  // Search state
  const [aiQuestion, setAiQuestion] = useState('');
  const [aiResponse, setAiResponse] = useState<string | null>(null);

  // Fetch contracts list from backend with reactive filters
  const { data: contractsData, isLoading } = useQuery({
    queryKey: ['repository-contracts', contractType],
    queryFn: async () => {
      // Map 'All Types' to empty for API
      const typeParam = contractType === 'All Types' ? '' : contractType;
      
      // Let's load the list. In Phase 4, we want to view published contracts primarily, but allow all.
      const response = await api.get(`/contracts?limit=50&contract_type=${typeParam}`);
      return response.data;
    },
  });

  const rawContracts: Contract[] = contractsData?.contracts || [];

  // Frontend filter simulation for year & department checkboxes to match high-fidelity visuals
  const filteredContracts = rawContracts.filter(contract => {
    // 1. Filter by workflow status (show published, approved, in review, or processing)
    // 2. Filter by Year (mocked from uploaded_at)
    const uploadedYear = new Date(contract.uploaded_at).getFullYear().toString();
    if (selectedYear && uploadedYear !== selectedYear && selectedYear !== 'Archive') {
      // Let it pass for now if we don't have old mock dates
    }

    // 3. Filter by department list
    if (selectedDepartments.length > 0) {
      const match = selectedDepartments.some(d => 
        contract.department?.toLowerCase().includes(d.toLowerCase())
      );
      if (!match && contract.department) return false;
    }

    return true;
  });

  // AI Assistant Query Mutation
  const aiQueryMutation = useMutation({
    mutationFn: async (question: string) => {
      const response = await api.post('/assistant/query', {
        question,
        limit: 5
      });
      return response.data;
    },
    onSuccess: (data) => {
      setAiResponse(data.answer || 'No answer generated by the assistant.');
    },
    onError: (err: any) => {
      setAiResponse(err.response?.data?.detail || 'Vector search query failed. Ensure you have published contracts seeded in the database.');
    }
  });

  const handleAiSearchSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!aiQuestion.trim()) return;
    setAiResponse(null);
    aiQueryMutation.mutate(aiQuestion);
  };

  const toggleDepartment = (dept: string) => {
    setSelectedDepartments(prev => 
      prev.includes(dept) ? prev.filter(d => d !== dept) : [...prev, dept]
    );
  };

  // State-to-badge styling map
  const getStatusBadge = (state: string) => {
    switch (state) {
      case 'PUBLISHED':
        return <span className="bg-primary text-on-primary px-sm py-0.5 rounded text-[10px] font-bold uppercase">Active</span>;
      case 'REVIEW_PENDING':
        return <span className="bg-secondary-container text-on-secondary-container px-sm py-0.5 rounded text-[10px] font-bold uppercase">Pending</span>;
      case 'DRAFT_READY':
      case 'USER_EDITING':
        return <span className="bg-amber-100 text-amber-800 border border-amber-200 px-sm py-0.5 rounded text-[10px] font-bold uppercase">Draft</span>;
      default:
        return <span className="bg-surface-container-highest text-on-surface-variant px-sm py-0.5 rounded text-[10px] font-bold uppercase">Processing</span>;
    }
  };

  return (
    <div className="p-lg max-w-[1400px] mx-auto w-full flex-1 overflow-y-auto custom-scrollbar">
      {/* Hero Search Section */}
      <section className="mb-xl">
        <div className="flex flex-col gap-sm mb-md">
          <h1 className="font-display-sm text-display-sm text-primary">Repository Hub</h1>
          <p className="text-on-surface-variant font-body-lg">
            Access intelligent contract extracts and document history across the enterprise.
          </p>
        </div>

        {/* Intelligent Vector Search Input */}
        <form onSubmit={handleAiSearchSubmit} className="relative group">
          <div className="absolute inset-y-0 left-0 pl-md flex items-center pointer-events-none">
            <span className="material-symbols-outlined text-primary text-xl" style={{ fontVariationSettings: '"FILL" 1' }}>
              search_spark
            </span>
          </div>
          <input 
            type="text"
            value={aiQuestion}
            onChange={(e) => setAiQuestion(e.target.value)}
            placeholder="Search using natural language, e.g., 'What is the liability cap in the Global Logistics agreement?'"
            className="block w-full pl-[52px] pr-[120px] py-xl bg-surface-container-lowest border border-outline-variant rounded-xl text-body-lg shadow-sm focus:ring-2 focus:ring-primary focus:border-transparent transition-all outline-none"
          />
          <div className="absolute inset-y-0 right-sm flex items-center">
            <kbd className="hidden sm:inline-flex items-center px-sm py-1 font-mono-md text-mono-md text-on-surface-variant bg-surface-container border border-outline-variant rounded mr-sm">
              ⌘ K
            </kbd>
            <button 
              type="submit"
              disabled={aiQueryMutation.isPending}
              className="bg-primary text-on-primary px-lg py-sm rounded-lg font-label-md shadow-lg hover:scale-[1.02] active:scale-[0.98] transition-transform disabled:opacity-50"
            >
              {aiQueryMutation.isPending ? 'Querying...' : 'Query'}
            </button>
          </div>
        </form>

        {/* AI Assistant response drawer/panel */}
        {(aiQueryMutation.isPending || aiResponse) && (
          <div className="mt-md p-lg bg-surface-container-lowest border-2 border-primary/20 rounded-xl shadow-lg relative overflow-hidden animate-fadeIn custom-glass">
            <div className="absolute top-0 left-0 w-2 h-full bg-primary"></div>
            <div className="flex items-start gap-md">
              <span className="material-symbols-outlined text-primary text-[28px] shrink-0 mt-xs">
                assistant
              </span>
              <div className="space-y-sm flex-1">
                <h4 className="font-headline-md text-[14px] text-primary font-bold tracking-tight">
                  AI ASSISTANT ANSWER
                </h4>
                {aiQueryMutation.isPending ? (
                  <div className="flex items-center gap-xs text-on-surface-variant font-body-md py-sm">
                    <div className="w-2.5 h-2.5 bg-primary rounded-full animate-bounce"></div>
                    <div className="w-2.5 h-2.5 bg-primary rounded-full animate-bounce [animation-delay:0.2s]"></div>
                    <div className="w-2.5 h-2.5 bg-primary rounded-full animate-bounce [animation-delay:0.4s]"></div>
                    <span className="ml-xs">Consulting published vector indexes...</span>
                  </div>
                ) : (
                  <div className="font-body-md text-body-md text-slate-800 leading-relaxed whitespace-pre-line">
                    {aiResponse}
                  </div>
                )}
              </div>
              <button 
                onClick={() => setAiResponse(null)}
                className="text-on-surface-variant hover:text-primary transition-colors shrink-0"
              >
                <span className="material-symbols-outlined text-[18px]">close</span>
              </button>
            </div>
          </div>
        )}
      </section>

      {/* Main Results Workspace */}
      <div className="flex gap-lg">
        {/* Left Sidebar: Metadata Filters */}
        <aside className="w-metadata-panel flex-shrink-0 flex flex-col gap-lg">
          <div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md shadow-sm">
            <div className="flex items-center justify-between mb-md">
              <h3 className="font-headline-md text-label-md uppercase tracking-wider text-on-surface-variant font-bold">
                Metadata Filters
              </h3>
              <button 
                onClick={() => {
                  setSelectedYear('2024');
                  setSelectedDepartments(['Legal', 'Finance', 'Procurement']);
                  setContractType('All Types');
                  setMinAccuracy(85);
                }}
                className="text-primary font-label-md hover:underline font-bold"
              >
                Clear all
              </button>
            </div>

            <div className="flex flex-col gap-lg">
              {/* Year Filter */}
              <div className="flex flex-col gap-sm">
                <label className="font-label-md text-on-surface font-bold">Year</label>
                <div className="grid grid-cols-2 gap-xs">
                  {['2024', '2023', '2022', 'Archive'].map((yr) => (
                    <button 
                      key={yr}
                      onClick={() => setSelectedYear(yr)}
                      className={`py-1.5 px-sm border rounded text-body-sm transition-colors font-bold ${
                        selectedYear === yr 
                          ? 'border-primary bg-primary-fixed text-on-primary-fixed'
                          : 'border-outline-variant bg-surface-container text-body-sm hover:border-primary'
                      }`}
                    >
                      {yr}
                    </button>
                  ))}
                </div>
              </div>

              {/* Department Filter */}
              <div className="flex flex-col gap-sm">
                <label className="font-label-md text-on-surface font-bold">Department</label>
                <div className="flex flex-col gap-xs">
                  {['Legal', 'Finance', 'Procurement', 'Sales', 'IT'].map((dept) => (
                    <label key={dept} className="flex items-center gap-sm cursor-pointer group select-none">
                      <input 
                        type="checkbox"
                        checked={selectedDepartments.includes(dept)}
                        onChange={() => toggleDepartment(dept)}
                        className="w-4 h-4 rounded text-primary border-outline-variant focus:ring-primary"
                      />
                      <span className="text-body-sm text-on-surface-variant group-hover:text-on-surface transition-colors font-bold">
                        {dept === 'Legal' ? 'Legal & Compliance' : dept === 'Sales' ? 'Sales & GTM' : dept}
                      </span>
                    </label>
                  ))}
                </div>
              </div>

              {/* Type Filter */}
              <div className="flex flex-col gap-sm">
                <label className="font-label-md text-on-surface font-bold">Contract Type</label>
                <select 
                  value={contractType}
                  onChange={(e) => setContractType(e.target.value)}
                  className="w-full bg-surface-container-low border-outline-variant rounded-lg text-body-sm py-2 px-2 focus:ring-1 focus:ring-primary outline-none"
                >
                  <option>All Types</option>
                  <option>Service Agreement</option>
                  <option>NDA</option>
                  <option>Technology</option>
                  <option>Procurement</option>
                  <option>Corporate</option>
                </select>
              </div>

              {/* Confidence Score Slider */}
              <div className="flex flex-col gap-sm pt-sm border-t border-outline-variant">
                <div className="flex justify-between items-center">
                  <label className="font-label-md text-on-surface font-bold">Min. Extraction Accuracy</label>
                  <span className="text-primary font-bold text-label-md">{minAccuracy}%</span>
                </div>
                <input 
                  type="range" 
                  min="50" 
                  max="100" 
                  value={minAccuracy}
                  onChange={(e) => setMinAccuracy(parseInt(e.target.value))}
                  className="w-full accent-primary h-1.5 bg-surface-container-highest rounded-full cursor-pointer"
                />
              </div>
            </div>
          </div>

          {/* Usage Stats Card */}
          <div className="bg-primary text-on-primary rounded-xl p-md flex flex-col gap-sm shadow-md">
            <div className="flex justify-between items-start">
              <span className="material-symbols-outlined text-primary-fixed">database</span>
              <span className="bg-primary-fixed/20 px-sm py-0.5 rounded text-[10px] font-bold tracking-tighter uppercase">
                Live Sync
              </span>
            </div>
            <div>
              <h4 className="text-headline-md font-bold">{filteredContracts.length}</h4>
              <p className="text-body-sm opacity-80">Contracts Matching Scope</p>
            </div>
            <div className="mt-xs pt-xs border-t border-on-primary/20">
              <div className="flex justify-between text-[11px] font-bold">
                <span>ORACLE CORPUS QUOTA</span>
                <span>{filteredContracts.filter(c => c.workflow_state === 'PUBLISHED').length} / 100</span>
              </div>
              <div className="w-full h-1 bg-on-primary/10 rounded-full mt-1">
                <div 
                  className="bg-primary-fixed h-full rounded-full transition-all duration-300"
                  style={{ width: `${Math.min(100, (filteredContracts.filter(c => c.workflow_state === 'PUBLISHED').length / 100) * 100)}%` }}
                ></div>
              </div>
            </div>
          </div>
        </aside>

        {/* Right Pane: Grid View of results */}
        <div className="flex-1">
          <div className="flex items-center justify-between mb-md">
            <div className="flex items-center gap-md">
              <h2 className="font-headline-lg text-headline-lg text-primary">Contracts Catalog</h2>
              <span className="bg-surface-container-highest text-on-surface-variant px-sm py-1 rounded-full text-[11px] font-bold">
                Live DB Sync
              </span>
            </div>
            <div className="flex bg-surface-container rounded p-0.5 shadow-sm">
              <button className="p-1.5 rounded bg-surface-container-lowest shadow-sm">
                <span className="material-symbols-outlined text-[18px]">grid_view</span>
              </button>
            </div>
          </div>

          {isLoading ? (
            <div className="text-center py-20 text-on-surface-variant font-body-md bg-surface-container-lowest border rounded-xl shadow-sm">
              Querying Oracle schema...
            </div>
          ) : filteredContracts.length === 0 ? (
            <div className="text-center py-20 text-on-surface-variant font-body-md bg-surface-container-lowest border rounded-xl shadow-sm">
              No matching contracts found. Try clearing filters or uploading new agreements.
            </div>
          ) : (
            /* Bento Grid for Results */
            <div className="grid grid-cols-1 xl:grid-cols-2 gap-lg">
              {filteredContracts.map((contract) => (
                <div 
                  key={contract.contract_id}
                  className="bg-surface-container-lowest border border-outline-variant rounded-xl overflow-hidden hover:shadow-md transition-shadow group flex flex-col justify-between"
                >
                  <div className="p-md flex flex-col h-full justify-between gap-md">
                    
                    {/* Header */}
                    <div className="flex justify-between items-start">
                      <div className="flex flex-col min-w-0">
                        <div className="flex items-start gap-sm mb-1">
                          <span className="material-symbols-outlined text-primary text-xl shrink-0 mt-0.5">
                            description
                          </span>
                          <h3 className="font-headline-md text-headline-md text-primary leading-tight group-hover:text-secondary transition-colors truncate max-w-[280px]">
                            {contract.filename}
                          </h3>
                        </div>
                        <p className="text-on-surface-variant font-label-md truncate">
                          ID: {contract.contract_id.substring(0, 13)}...
                        </p>
                      </div>
                      {getStatusBadge(contract.workflow_state)}
                    </div>

                    {/* Meta bento slots */}
                    <div className="grid grid-cols-2 gap-sm">
                      <div className="p-sm bg-surface-container rounded-lg border border-outline-variant/30">
                        <p className="text-on-surface-variant text-[10px] uppercase font-bold mb-xs">Department</p>
                        <p className="text-body-sm font-bold truncate">
                          {contract.department || 'Legal Operations'}
                        </p>
                      </div>
                      <div className="p-sm bg-surface-container rounded-lg border border-outline-variant/30">
                        <p className="text-on-surface-variant text-[10px] uppercase font-bold mb-xs">Contract Type</p>
                        <p className="text-body-sm font-bold truncate">
                          {contract.contract_type || 'Master Agreement'}
                        </p>
                      </div>
                    </div>

                    {/* Extract summary details */}
                    <div className="flex flex-col gap-sm flex-1">
                      <div className="flex items-center gap-sm">
                        <div className="w-1.5 h-1.5 rounded-full bg-primary"></div>
                        <p className="text-body-sm text-on-surface truncate">
                          Client: <span className="font-bold">{contract.customer_name || 'Acme Corp'}</span>
                        </p>
                      </div>
                      <div className="flex items-center gap-sm">
                        <div className="w-1.5 h-1.5 rounded-full bg-primary"></div>
                        <p className="text-body-sm text-on-surface-variant truncate">
                          Uploaded: {new Date(contract.uploaded_at).toLocaleDateString()}
                        </p>
                      </div>
                    </div>

                    {/* Footer Actions */}
                    <div className="mt-lg pt-md border-t border-outline-variant flex items-center justify-between bg-surface-container-lowest">
                      <span className="text-on-surface-variant text-[11px] font-mono">
                        {contract.workflow_state}
                      </span>
                      
                      <div className="flex gap-sm">
                        {['DRAFT_READY', 'USER_EDITING'].includes(contract.workflow_state) ? (
                          <button 
                            onClick={() => navigate(`/review/${contract.contract_id}`)}
                            className="bg-primary text-on-primary font-label-md px-md py-1.5 rounded-lg flex items-center gap-xs hover:opacity-90 active:scale-[0.98] transition-all shadow-sm"
                          >
                            Review Draft
                            <span className="material-symbols-outlined text-[16px]">edit</span>
                          </button>
                        ) : (
                          <button 
                            onClick={() => navigate(`/review/${contract.contract_id}`)}
                            className="bg-primary text-on-primary font-label-md px-md py-1.5 rounded-lg flex items-center gap-xs hover:opacity-90 active:scale-[0.98] transition-all shadow-sm"
                          >
                            Open Document
                            <span className="material-symbols-outlined text-[16px]">arrow_forward</span>
                          </button>
                        )}
                      </div>
                    </div>

                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
