import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useQuery, useMutation } from '@tanstack/react-query';
import api from '../services/api';

interface Contract {
  contract_id: string;
  filename: string;
  customer_name: string;
  contract_type: string;
  department: string;
  workflow_state: string;
  uploaded_at: string;
  approved_at?: string;
  published_at?: string;
}

export default function Repository() {
  const navigate = useNavigate();

  // Filters State
  const [selectedYear, setSelectedYear] = useState<string>('2024');
  const [selectedDepartments, setSelectedDepartments] = useState<string[]>(['Legal', 'Finance', 'Procurement']);
  const [contractType, setContractType] = useState<string>('All Types');
  const [minAccuracy, setMinAccuracy] = useState<number>(85);
  
  // Search state
  const [aiQuestion, setAiQuestion] = useState('');
  const [aiResponse, setAiResponse] = useState<string | null>(null);

  // Fetch contracts list from backend with reactive filters
  const { data: contractsData, isLoading } = useQuery({
    queryKey: ['repository-contracts', contractType],
    queryFn: async () => {
      // Map 'All Types' to empty for API
      const typeParam = contractType === 'All Types' ? '' : contractType;
      
      // Let's load the list. In Phase 4, we want to view published contracts primarily, but allow all.
      const response = await api.get(`/contracts?limit=50&contract_type=${typeParam}`);
      return response.data;
    },
  });

  const rawContracts: Contract[] = contractsData?.contracts || [];

  // Frontend filter simulation for year & department checkboxes to match high-fidelity visuals
  const filteredContracts = rawContracts.filter(contract => {
    // 1. Filter by workflow status (show published, approved, in review, or processing)
    // 2. Filter by Year (mocked from uploaded_at)
    const uploadedYear = new Date(contract.uploaded_at).getFullYear().toString();
    if (selectedYear && uploadedYear !== selectedYear && selectedYear !== 'Archive') {
      // Let it pass for now if we don't have old mock dates
    }

    // 3. Filter by department list
    if (selectedDepartments.length > 0) {
      const match = selectedDepartments.some(d => 
        contract.department?.toLowerCase().includes(d.toLowerCase())
      );
      if (!match && contract.department) return false;
    }

    return true;
  });

  // AI Assistant Query Mutation
  const aiQueryMutation = useMutation({
    mutationFn: async (question: string) => {
      const response = await api.post('/assistant/query', {
        question,
        limit: 5
      });
      return response.data;
    },
    onSuccess: (data) => {
      setAiResponse(data.answer || 'No answer generated by the assistant.');
    },
    onError: (err: any) => {
      setAiResponse(err.response?.data?.detail || 'Vector search query failed. Ensure you have published contracts seeded in the database.');
    }
  });

  const handleAiSearchSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!aiQuestion.trim()) return;
    setAiResponse(null);
    aiQueryMutation.mutate(aiQuestion);
  };

  const toggleDepartment = (dept: string) => {
    setSelectedDepartments(prev => 
      prev.includes(dept) ? prev.filter(d => d !== dept) : [...prev, dept]
    );
  };

  // State-to-badge styling map
  const getStatusBadge = (state: string) => {
    switch (state) {
      case 'PUBLISHED':
        return <span className="bg-primary text-on-primary px-sm py-0.5 rounded text-[10px] font-bold uppercase">Active</span>;
      case 'REVIEW_PENDING':
        return <span className="bg-secondary-container text-on-secondary-container px-sm py-0.5 rounded text-[10px] font-bold uppercase">Pending</span>;
      case 'DRAFT_READY':
      case 'USER_EDITING':
        return <span className="bg-amber-100 text-amber-800 border border-amber-200 px-sm py-0.5 rounded text-[10px] font-bold uppercase">Draft</span>;
      default:
        return <span className="bg-surface-container-highest text-on-surface-variant px-sm py-0.5 rounded text-[10px] font-bold uppercase">Processing</span>;
    }
  };

  return (
    <div className="p-lg max-w-[1400px] mx-auto w-full flex-1 overflow-y-auto custom-scrollbar bg-surface/30">
      {/* Hero Search Section */}
      <section className="mb-xl border-b border-slate-100 pb-lg">
        <div className="flex flex-col gap-xs mb-lg">
          <h1 className="font-display-sm text-display-sm text-primary font-black tracking-tight">Repository Hub</h1>
          <p className="text-on-surface-variant font-body-lg">
            Access intelligent contract extracts and unified semantic query history across the enterprise.
          </p>
        </div>

        {/* Intelligent Vector Search Input */}
        <form onSubmit={handleAiSearchSubmit} className="relative group">
          <div className="absolute inset-0 bg-gradient-to-r from-blue-500/10 to-indigo-500/10 rounded-2xl blur opacity-30 group-hover:opacity-60 transition-opacity duration-300"></div>
          
          <div className="relative bg-white border border-outline-variant/40 rounded-2xl shadow-sm hover:shadow-md focus-within:ring-2 focus-within:ring-primary/20 focus-within:border-primary transition-all duration-300 flex items-center overflow-hidden">
            <div className="pl-lg flex items-center pointer-events-none">
              <span className="material-symbols-outlined text-primary text-[24px] font-bold" style={{ fontVariationSettings: '"FILL" 1' }}>
                search_spark
              </span>
            </div>
            <input 
              type="text"
              value={aiQuestion}
              onChange={(e) => setAiQuestion(e.target.value)}
              placeholder="Query agreements using natural language, e.g., 'What is the liability cap in the Global Logistics contract?'"
              className="w-full pl-md pr-32 py-xl bg-transparent border-none text-body-lg focus:ring-0 outline-none font-semibold placeholder:text-slate-400 placeholder:font-normal"
            />
            <div className="absolute right-sm flex items-center gap-xs">
              <kbd className="hidden sm:inline-flex items-center px-sm py-[3px] font-mono text-[10px] font-extrabold text-on-surface-variant bg-slate-100 border border-slate-200 rounded shadow-sm">
                CTRL K
              </kbd>
              <button 
                type="submit"
                disabled={aiQueryMutation.isPending}
                className="bg-primary hover:bg-primary/95 text-on-primary px-lg py-2.5 rounded-xl font-label-md shadow-md hover:scale-[1.02] active:scale-[0.98] transition-transform disabled:opacity-50 font-bold shrink-0"
              >
                {aiQueryMutation.isPending ? 'Running...' : 'Query'}
              </button>
            </div>
          </div>
        </form>

        {/* AI Assistant response drawer/panel */}
        {(aiQueryMutation.isPending || aiResponse) && (
          <div className="mt-md p-lg bg-white border border-primary/20 rounded-2xl shadow-lg relative overflow-hidden animate-fadeIn custom-glass select-none">
            <div className="absolute top-0 left-0 w-1.5 h-full bg-gradient-to-b from-blue-600 to-indigo-600"></div>
            <div className="flex items-start gap-md">
              <span className="material-symbols-outlined text-primary text-[28px] shrink-0 mt-xs" style={{ fontVariationSettings: '"FILL" 1' }}>
                assistant
              </span>
              <div className="space-y-sm flex-1">
                <h4 className="text-[11px] text-primary font-black tracking-wider uppercase">
                  ContractLens AI Assistant
                </h4>
                {aiQueryMutation.isPending ? (
                  <div className="flex items-center gap-xs text-on-surface-variant font-body-md py-sm font-semibold">
                    <div className="w-2 h-2 bg-primary rounded-full animate-bounce"></div>
                    <div className="w-2 h-2 bg-primary rounded-full animate-bounce [animation-delay:0.2s]"></div>
                    <div className="w-2 h-2 bg-primary rounded-full animate-bounce [animation-delay:0.4s]"></div>
                    <span className="ml-xs text-[12px] text-slate-500 font-semibold">Consulting vector store index...</span>
                  </div>
                ) : (
                  <div className="font-body-md text-body-md text-slate-800 leading-relaxed whitespace-pre-line font-medium bg-slate-50/50 p-md border border-slate-100 rounded-xl">
                    {aiResponse}
                  </div>
                )}
              </div>
              <button 
                onClick={() => setAiResponse(null)}
                className="text-on-surface-variant hover:text-primary transition-colors shrink-0 w-6 h-6 rounded-full hover:bg-slate-100 flex items-center justify-center"
              >
                <span className="material-symbols-outlined text-[16px] font-bold">close</span>
              </button>
            </div>
          </div>
        )}
      </section>

      {/* Main Results Workspace */}
      <div className="flex gap-lg items-start">
        {/* Left Sidebar: Metadata Filters */}
        <aside className="w-metadata-panel flex-shrink-0 flex flex-col gap-lg select-none">
          <div className="bg-white border border-outline-variant/30 rounded-2xl p-md shadow-sm">
            <div className="flex items-center justify-between mb-md border-b border-slate-100 pb-sm">
              <h3 className="text-[10px] uppercase tracking-wider text-on-surface-variant font-extrabold">
                Filters
              </h3>
              <button 
                onClick={() => {
                  setSelectedYear('2024');
                  setSelectedDepartments(['Legal', 'Finance', 'Procurement']);
                  setContractType('All Types');
                  setMinAccuracy(85);
                }}
                className="text-primary hover:text-primary/80 font-bold text-[11px] underline"
              >
                Clear all
              </button>
            </div>

            <div className="flex flex-col gap-lg">
              {/* Year Filter */}
              <div className="flex flex-col gap-xs">
                <label className="text-[11px] uppercase tracking-wider text-slate-400 font-extrabold">Year</label>
                <div className="grid grid-cols-2 gap-xs">
                  {['2024', '2023', '2022', 'Archive'].map((yr) => (
                    <button 
                      key={yr}
                      onClick={() => setSelectedYear(yr)}
                      className={`py-1.5 px-xs border rounded-xl text-[12px] transition-colors font-extrabold select-none ${
                        selectedYear === yr 
                          ? 'border-primary bg-primary-fixed text-primary'
                          : 'border-slate-100 bg-slate-50 text-slate-500 hover:border-primary/30 hover:bg-white'
                      }`}
                    >
                      {yr}
                    </button>
                  ))}
                </div>
              </div>

              {/* Department Filter */}
              <div className="flex flex-col gap-xs">
                <label className="text-[11px] uppercase tracking-wider text-slate-400 font-extrabold">Department</label>
                <div className="flex flex-col gap-xs pt-xs">
                  {['Legal', 'Finance', 'Procurement', 'Sales', 'IT'].map((dept) => (
                    <label key={dept} className="flex items-center gap-sm cursor-pointer group select-none">
                      <input 
                        type="checkbox"
                        checked={selectedDepartments.includes(dept)}
                        onChange={() => toggleDepartment(dept)}
                        className="w-4 h-4 rounded text-primary border-outline-variant/50 focus:ring-primary cursor-pointer"
                      />
                      <span className="text-body-sm text-slate-600 font-semibold group-hover:text-primary transition-colors">
                        {dept === 'Legal' ? 'Legal & Compliance' : dept === 'Sales' ? 'Sales & GTM' : dept}
                      </span>
                    </label>
                  ))}
                </div>
              </div>

              {/* Type Filter */}
              <div className="flex flex-col gap-xs">
                <label className="text-[11px] uppercase tracking-wider text-slate-400 font-extrabold">Contract Type</label>
                <select 
                  value={contractType}
                  onChange={(e) => setContractType(e.target.value)}
                  className="w-full bg-slate-50 hover:bg-slate-100/50 border border-slate-200 hover:border-slate-300 rounded-xl text-body-sm py-2 px-2.5 focus:ring-2 focus:ring-primary/20 focus:border-primary outline-none transition-all font-semibold"
                >
                  <option>All Types</option>
                  <option>Service Agreement</option>
                  <option>NDA</option>
                  <option>Technology</option>
                  <option>Procurement</option>
                  <option>Corporate</option>
                </select>
              </div>

              {/* Confidence Score Slider */}
              <div className="flex flex-col gap-xs pt-md border-t border-slate-100">
                <div className="flex justify-between items-center mb-1">
                  <label className="text-[11px] uppercase tracking-wider text-slate-400 font-extrabold">Min. Accuracy</label>
                  <span className="text-primary font-black text-body-sm">{minAccuracy}%</span>
                </div>
                <input 
                  type="range" 
                  min="50" 
                  max="100" 
                  value={minAccuracy}
                  onChange={(e) => setMinAccuracy(parseInt(e.target.value))}
                  className="w-full accent-primary h-1.5 bg-slate-100 rounded-full cursor-pointer hover:accent-primary/95"
                />
              </div>
            </div>
          </div>

          {/* Usage Stats Card */}
          <div className="bg-gradient-to-br from-slate-50 to-indigo-50/50 border border-slate-200/50 rounded-2xl p-lg flex flex-col gap-sm shadow-sm relative overflow-hidden group">
            <div className="absolute top-0 right-0 w-20 h-20 bg-indigo-100/30 rounded-full blur-xl -mr-4 -mt-4"></div>
            
            <div className="flex justify-between items-start z-10">
              <span className="material-symbols-outlined text-indigo-600 text-[24px]">database</span>
              <span className="bg-indigo-100 text-indigo-700 px-sm py-[2px] border border-indigo-200/50 rounded-full text-[9px] font-extrabold tracking-wider uppercase select-none">
                Schema Active
              </span>
            </div>
            <div className="z-10 select-none">
              <h4 className="font-display-sm text-[32px] font-black leading-none text-slate-800 mb-1">{filteredContracts.length}</h4>
              <p className="text-[11px] text-slate-500 font-bold">Contracts Matching Scope</p>
            </div>
            <div className="mt-xs pt-xs border-t border-slate-200/60 z-10 select-none">
              <div className="flex justify-between text-[9px] font-extrabold uppercase tracking-wider text-slate-500 mb-1.5">
                <span>Oracle Corpus Quota</span>
                <span>{filteredContracts.filter(c => c.workflow_state === 'PUBLISHED').length} / 100</span>
              </div>
              <div className="w-full h-1.5 bg-slate-200 rounded-full overflow-hidden shadow-inner">
                <div 
                  className="bg-indigo-600 h-full rounded-full transition-all duration-700 ease-out"
                  style={{ width: `${Math.min(100, (filteredContracts.filter(c => c.workflow_state === 'PUBLISHED').length / 100) * 100)}%` }}
                ></div>
              </div>
            </div>
          </div>
        </aside>

        {/* Right Pane: Grid View of results */}
        <div className="flex-1 min-w-0">
          <div className="flex items-center justify-between mb-md border-b border-slate-100 pb-sm select-none">
            <div className="flex items-center gap-md">
              <h2 className="font-headline-lg text-headline-lg text-primary font-black tracking-tight">Contracts Catalog</h2>
              <span className="bg-slate-100 text-slate-600 px-sm py-[2px] rounded-full text-[10px] font-extrabold uppercase tracking-wider">
                Live Schema
              </span>
            </div>
            <div className="flex bg-slate-100 border border-slate-200/50 rounded-xl p-0.5 shadow-inner">
              <button className="p-1.5 rounded-lg bg-white shadow-sm text-primary">
                <span className="material-symbols-outlined text-[18px] font-bold">grid_view</span>
              </button>
            </div>
          </div>

          {isLoading ? (
            <div className="text-center py-20 text-on-surface-variant font-body-md bg-white border border-outline-variant/30 rounded-2xl shadow-sm">
              Querying Oracle schema...
            </div>
          ) : filteredContracts.length === 0 ? (
            <div className="text-center py-20 text-on-surface-variant font-body-md bg-white border border-outline-variant/30 rounded-2xl shadow-sm">
              No matching contracts found. Try clearing filters or uploading new agreements.
            </div>
          ) : (
            /* Bento Grid for Results */
            <div className="grid grid-cols-1 xl:grid-cols-2 gap-lg pb-md">
              {filteredContracts.map((contract) => (
                <div 
                  key={contract.contract_id}
                  className="bg-white border border-outline-variant/30 hover:border-primary/20 rounded-2xl overflow-hidden hover:shadow-md hover:-translate-y-0.5 transition-all duration-300 group flex flex-col justify-between h-[250px]"
                >
                  <div className="p-md flex flex-col h-full justify-between gap-sm">
                    
                    {/* Header */}
                    <div className="flex justify-between items-start gap-sm">
                      <div className="flex items-start gap-xs min-w-0">
                        <span className="material-symbols-outlined text-primary text-[20px] shrink-0 mt-0.5" style={{ fontVariationSettings: '"FILL" 1' }}>
                          description
                        </span>
                        <div className="min-w-0">
                          <h3 className="font-body-md text-body-md font-extrabold text-primary group-hover:text-indigo-600 transition-colors truncate max-w-[200px]" title={contract.filename}>
                            {contract.filename}
                          </h3>
                          <p className="text-[10px] text-slate-400 font-mono tracking-tighter truncate">
                            ID: {contract.contract_id.substring(0, 16)}
                          </p>
                        </div>
                      </div>
                      <div className="shrink-0">
                        {getStatusBadge(contract.workflow_state)}
                      </div>
                    </div>

                    {/* Meta bento slots */}
                    <div className="grid grid-cols-2 gap-xs select-none">
                      <div className="p-sm bg-slate-50 border border-slate-100 rounded-xl">
                        <p className="text-slate-400 text-[9px] uppercase font-extrabold mb-[2px]">Department</p>
                        <p className="text-body-sm font-extrabold text-slate-700 truncate">
                          {contract.department || 'Legal Operations'}
                        </p>
                      </div>
                      <div className="p-sm bg-slate-50 border border-slate-100 rounded-xl">
                        <p className="text-slate-400 text-[9px] uppercase font-extrabold mb-[2px]">Contract Type</p>
                        <p className="text-body-sm font-extrabold text-slate-700 truncate">
                          {contract.contract_type || 'Master Agreement'}
                        </p>
                      </div>
                    </div>

                    {/* Extract summary details */}
                    <div className="flex flex-col gap-xs flex-grow justify-center pl-xs">
                      <div className="flex items-center gap-sm">
                        <div className="w-1.5 h-1.5 rounded-full bg-slate-300 group-hover:bg-primary transition-colors"></div>
                        <p className="text-[12px] text-slate-700 font-semibold truncate">
                          Partner: <span className="font-extrabold text-primary">{contract.customer_name || 'Acme Corp'}</span>
                        </p>
                      </div>
                      <div className="flex items-center gap-sm">
                        <div className="w-1.5 h-1.5 rounded-full bg-slate-300 group-hover:bg-primary transition-colors"></div>
                        <p className="text-[12px] text-slate-500 font-medium truncate">
                          Uploaded: {new Date(contract.uploaded_at).toLocaleDateString()}
                        </p>
                      </div>
                    </div>

                    {/* Footer Actions */}
                    <div className="pt-sm border-t border-slate-100 flex items-center justify-between select-none">
                      <span className="text-[9px] font-mono font-bold text-slate-400 bg-slate-100 px-sm py-[2px] rounded uppercase">
                        {contract.workflow_state}
                      </span>
                      
                      <div className="flex gap-sm">
                        {['DRAFT_READY', 'USER_EDITING'].includes(contract.workflow_state) ? (
                          <button 
                            onClick={() => navigate(`/review/${contract.contract_id}`)}
                            className="bg-primary hover:bg-primary/90 text-on-primary font-bold text-label-md px-md py-1.5 rounded-xl flex items-center gap-xs hover:scale-[1.02] active:scale-[0.98] transition-all shadow-sm"
                          >
                            Review Draft
                            <span className="material-symbols-outlined text-[16px] font-bold">edit</span>
                          </button>
                        ) : (
                          <button 
                            onClick={() => navigate(`/review/${contract.contract_id}`)}
                            className="bg-primary hover:bg-primary/90 text-on-primary font-bold text-label-md px-md py-1.5 rounded-xl flex items-center gap-xs hover:scale-[1.02] active:scale-[0.98] transition-all shadow-sm"
                          >
                            Open Document
                            <span className="material-symbols-outlined text-[16px] font-bold">arrow_forward</span>
                          </button>
                        )}
                      </div>
                    </div>

                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
